up
Signed-off-by: Jakub Mitura <jakub.mitura14@gmail.com>

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,21 +1,284 @@
-# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.241.1/containers/python-3/.devcontainer/base.Dockerfile
+## { Mitura start}
+#FROM nvidia/cuda:11.3.1-devel-ubuntu20.04
+FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04
 
-# [Choice] Python version (use -bullseye variants on local arm64/Apple Silicon): 3, 3.10, 3.9, 3.8, 3.7, 3.6, 3-bullseye, 3.10-bullseye, 3.9-bullseye, 3.8-bullseye, 3.7-bullseye, 3.6-bullseye, 3-buster, 3.10-buster, 3.9-buster, 3.8-buster, 3.7-buster, 3.6-buster
-ARG VARIANT="3.10-bullseye"
-FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}
+################################################################################
+# Prevent apt-get from prompting for keyboard choice
+#  https://superuser.com/questions/1356914/how-to-install-xserver-xorg-in-unattended-mode
+ENV DEBIAN_FRONTEND=noninteractive
 
-# [Choice] Node.js version: none, lts/*, 16, 14, 12, 10
-ARG NODE_VERSION="none"
-RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi
+# Remove any third-party apt sources to avoid issues with expiring keys.
+RUN rm -f /etc/apt/sources.list.d/*.list
 
-# [Optional] If your pip requirements rarely change, uncomment this section to add them to the image.
-# COPY requirements.txt /tmp/pip-tmp/
-# RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
-#    && rm -rf /tmp/pip-tmp
+# Install some basic utilities
+RUN apt-get update && apt-get install -y \
+    curl \
+    ca-certificates \
+    sudo \
+    git \
+    bzip2 \
+    libx11-6 \
+    build-essential \
+    wget\
+    manpages-dev\
+    g++\
+    gcc\
+    nodejs\
+    libssl-dev\
+    unzip\
+    #cuda-11.3\
+    #nvidia-cuda-toolkit-11-3\
+    && rm -rf /var/lib/apt/lists/*
 
-# [Optional] Uncomment this section to install additional OS packages.
-# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
-#     && apt-get -y install --no-install-recommends <your-package-list-here>
 
-# [Optional] Uncomment this line to install global node packages.
-# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
+
+## installing github CLI - https://github.com/cli/cli/blob/trunk/docs/install_linux.md
+RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
+RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
+RUN sudo apt update
+RUN sudo apt install gh
+RUN apt autoremove python3 -y
+
+
+
+# RUN add-apt-repository ppa:jonathonf/gcc-7.1
+# RUN apt-get update
+# RUN apt-get install gcc-7 g++-7
+
+
+# RUN apt-get install -y software-properties-common
+# RUN add-apt-repository ppa:ubuntu-toolchain-r/test
+# RUN apt install -y gcc-7 g++-7
+
+
+
+RUN mkdir /app
+WORKDIR /app
+
+RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
+RUN mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
+RUN wget https://developer.download.nvidia.com/compute/cuda/11.3.0/local_installers/cuda-repo-ubuntu2004-11-3-local_11.3.0-465.19.01-1_amd64.deb
+RUN dpkg -i cuda-repo-ubuntu2004-11-3-local_11.3.0-465.19.01-1_amd64.deb
+RUN apt-key add /var/cuda-repo-ubuntu2004-11-3-local/7fa2af80.pub
+RUN apt-get update
+RUN apt-get -y install cuda-11.3
+RUN apt-key add /var/cuda-repo-ubuntu2004-11-3-local/7fa2af80.pub
+## { Mitura end}
+
+
+
+################################################################################
+# Remove documentation to save hard drive space
+#  https://askubuntu.com/questions/129566/remove-documentation-to-save-hard-drive-space
+COPY etc/dpkg/dpkg.cfg.d/01_nodoc /etc/dpkg/dpkg.cfg.d/01_nodoc
+
+################################################################################
+# - update apt, set up certs, run netselect to get fast mirror
+# - reduce apt gravity
+# - and disable caching
+#   from https://blog.sleeplessbeastie.eu/2017/10/02/how-to-disable-the-apt-cache/
+# Note: in each RUN command "apt-get update" must be called before apt-get is used.
+RUN echo 'APT::Install-Recommends "0" ; APT::Install-Suggests "0" ;' >> /etc/apt/apt.conf && \
+    echo 'Dir::Cache::pkgcache "";\nDir::Cache::srcpkgcache "";' | tee /etc/apt/apt.conf.d/00_disable-cache-files
+
+################################################################################
+# get packages
+# - update (without update, old cached server addresses may be used and apt-get install may fail)
+# - install things
+#   - basic  tools
+#   - slicer dependencies
+#   - awesome window manager
+#   - install ca-certs to prevent - fatal: unable to access 'https://github.com/novnc/websockify/': server certificate verification failed. CAfile: none CRLfile: none
+RUN apt-get update -q -y && \
+    apt-get install -q -y \
+    vim net-tools curl \
+    libgl1-mesa-glx \
+    xserver-xorg-video-dummy \
+    libxrender1 \
+    libpulse0 \
+    libpulse-mainloop-glib0  \
+    libnss3  \
+    libxcomposite1 \
+    libxcursor1 \
+    libfontconfig1 \
+    libxrandr2 \
+    libasound2 \
+    libglu1 \
+    x11vnc \
+    awesome \
+    jq \
+    nautilus\
+    jupyter-core\
+    zip\
+    p7zip-full\
+    apt-utils\
+    octave\
+    kmod\
+    zlib1g\
+    python-dev\
+    bzip2\
+    cmake\
+    cuda-command-line-tools-11.3 \
+    libcublas-11.3 \
+    cuda-nvrtc-11.3\
+    libcufft-11.3 \
+    libcurand-11.3 \
+    libcusolver-11.3 \
+    libcusparse-11.3 \
+    libfreetype6-dev \
+    curl\
+    libzmq3-dev \
+    pkg-config\
+    software-properties-common\
+    libhdf5-serial-dev\
+    git && \
+    apt-get install -q -y --reinstall ca-certificates
+
+
+
+
+
+
+
+
+RUN set -eux; \
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
+		ca-certificates \
+# ERROR: no download agent available; install curl, wget, or fetch
+		curl \
+	; \
+	rm -rf /var/lib/apt/lists/*
+
+ENV JULIA_PATH /usr/local/julia
+ENV PATH $JULIA_PATH/bin:$PATH
+
+# https://julialang.org/juliareleases.asc
+# Julia (Binary signing key) <buildbot@julialang.org>
+ENV JULIA_GPG 3673DF529D9049477F76B37566E3C7DC03D6E495
+
+# https://julialang.org/downloads/
+ENV JULIA_VERSION 1.7.3
+
+RUN set -eux; \
+	\
+	savedAptMark="$(apt-mark showmanual)"; \
+	if ! command -v gpg > /dev/null; then \
+		apt-get update; \
+		apt-get install -y --no-install-recommends \
+			gnupg \
+			dirmngr \
+		; \
+		rm -rf /var/lib/apt/lists/*; \
+	fi; \
+	\
+# https://julialang.org/downloads/#julia-command-line-version
+# https://julialang-s3.julialang.org/bin/checksums/julia-1.7.3.sha256
+	arch="$(dpkg --print-architecture)"; \
+	case "$arch" in \
+		'amd64') \
+			url='https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.3-linux-x86_64.tar.gz'; \
+			sha256='9b2f4fa12d92b4dcc5d11dc66fb118c47681a76d3df8da064cc97573f2f5c739'; \
+			;; \
+		'armhf') \
+			url='https://julialang-s3.julialang.org/bin/linux/armv7l/1.7/julia-1.7.3-linux-armv7l.tar.gz'; \
+			sha256='e9de15c56b9b62727c69d10da4b8e90fa6609d2e94e9cfb9f99128dfb59a8677'; \
+			;; \
+		'arm64') \
+			url='https://julialang-s3.julialang.org/bin/linux/aarch64/1.7/julia-1.7.3-linux-aarch64.tar.gz'; \
+			sha256='d9e8b342c80ad1371520ed6d11f55b78aa60746737fbf57ecafd6a23b52dd71d'; \
+			;; \
+		'i386') \
+			url='https://julialang-s3.julialang.org/bin/linux/x86/1.7/julia-1.7.3-linux-i686.tar.gz'; \
+			sha256='c1e1a4f9a53affee269c7e740cb8bd46740f9021414459c3ab3bb2c540d9d499'; \
+			;; \
+		*) \
+			echo >&2 "error: current architecture ($arch) does not have a corresponding Julia binary release"; \
+			exit 1; \
+			;; \
+	esac; \
+	\
+	curl -fL -o julia.tar.gz.asc "$url.asc"; \
+	curl -fL -o julia.tar.gz "$url"; \
+	\
+	echo "$sha256 *julia.tar.gz" | sha256sum --strict --check -; \
+	\
+	export GNUPGHOME="$(mktemp -d)"; \
+	gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$JULIA_GPG"; \
+	gpg --batch --verify julia.tar.gz.asc julia.tar.gz; \
+	command -v gpgconf > /dev/null && gpgconf --kill all; \
+	rm -rf "$GNUPGHOME" julia.tar.gz.asc; \
+	\
+	mkdir "$JULIA_PATH"; \
+	tar -xzf julia.tar.gz -C "$JULIA_PATH" --strip-components 1; \
+	rm julia.tar.gz; \
+	\
+	apt-mark auto '.*' > /dev/null; \
+	[ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; \
+	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+	\
+# smoke test
+	julia --version
+
+#RUN mkdir ${HOME}/data
+#RUN mkdir "/home/sliceruser/data"
+# RUN apt-get dist-upgrade
+
+
+# RUN add-apt-repository ppa:ubuntu-toolchain-r/test
+# RUN apt-get update
+# RUN apt-get install -y  gcc --fix-missing
+# RUN apt-get upgrade -y libstdc++6 --fix-missing
+
+# set up user
+ENV NB_USER sliceruser
+ENV NB_UID 1000
+ENV HOME /home/${NB_USER}
+
+
+
+RUN adduser --disabled-password \
+    --gecos "Default user" \
+    --uid ${NB_UID} \
+    ${NB_USER}
+
+WORKDIR ${HOME}
+
+RUN chown -R ${NB_USER}  /usr/share/X11
+RUN chmod -R ugo+rwx /usr/share/X11
+RUN chown -R ${NB_USER}  /etc/X11
+RUN chmod -R ugo+rwx /etc/X11
+RUN chown -R ${NB_USER}  /tmp/
+RUN chmod -R ugo+rwx /tmp/
+# RUN chown -R ${NB_USER}  /dev/tty0
+# RUN chmod -R ugo+rwx /dev/tty0
+
+#RUN chown ${NB_USER} ${HOME} ${HOME}/data
+USER ${NB_USER}
+
+#login to github cli 
+# COPY mytoken.txt .
+# RUN gh auth login --with-token < mytoken.txt
+RUN git config --global user.name "Jakub Mitura"
+RUN git config --global user.email "jakub.mitura14@gmail.com"
+RUN git config -l
+
+
+RUN git clone https://github.com/jakubMitura14/MedPipe3DTutorial.git ${HOME}/data/mainCode
+
+#CMD ["/bin/bash"]
+################################################################################
+# Build-time metadata as defined at http://label-schema.org
+ARG BUILD_DATE
+ARG IMAGE
+ARG VCS_REF
+ARG VCS_URL
+LABEL org.label-schema.build-date=$BUILD_DATE \
+    org.label-schema.name=$IMAGE \
+    org.label-schema.vcs-ref=$VCS_REF \
+    org.label-schema.vcs-url=$VCS_URL \
+    org.label-schema.schema-version="1.0"
+
+
+
+ENTRYPOINT [ "/bin/bash", "-l", "-c" ]
